Save all gathered data as nodeinfo1 datatype
m-lab/nodeinfo pull request #16
Opened 2023-02-23 12:12 UTC by SaiedKazemi

This is a proof-of-concept implementation of an experiment that generates data that meets autoloading requirements.

Specifically, this POC implementation saves all gathered output from all commands specified in the configuration file as nodeinfo1 datatype (see api/node_info.go).

For testing and comparing purposes only, the old behavior is still supported but will be deleted (along with Makefile, config-old.json, config-new.json) once the changes are fully reviewed.

The changes in this POC successfully pass static analyzers and were tested as follows:

    go test ./...
    make
    make check

2023-02-23 14:47 UTC, stephen-soltesz reviewed
I haven't looked yet, but I already love this.

> *[Reviewable](https://reviewable.io/reviews/m-lab/nodeinfo/16#-:-NOyjXv2BXwW0xq48Wxi:b-uefrdp)* status: 0 of 1 approvals obtained



<!-- Sent from Reviewable.io -->

2023-02-24 01:02 UTC, stephen-soltesz reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/nodeinfo/16)* status: 0 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[`config-new.json` line 7 at r1](https://reviewable.io/reviews/m-lab/nodeinfo/16#-NP-uu8qAi0KjyI1JzoE:-NP-uu8qAi0KjyI1JzoF:b-cto8fp) ([raw file](https://github.com/m-lab/nodeinfo/blob/012a82c492f8859efe2f1c6190021102841918c1/config-new.json#L7)):*
> ```JSON
>       ],
>       "Datatype": "lshw",
>       "Filename": "lshw.json"
> ```

Does the new config need a `Filename` any more?
___
*[`config-new.json` line 73 at r1](https://reviewable.io/reviews/m-lab/nodeinfo/16#-NP-v0HX4YcwsAMEGiJx:-NP-v0HX4YcwsAMEGiJy:bqwxo2r) ([raw file](https://github.com/m-lab/nodeinfo/blob/012a82c492f8859efe2f1c6190021102841918c1/config-new.json#L73)):*
> ```JSON
>       "Filename": "os-release.json"
>    },
>    {
> ```

Discussed with Shelbie, and I think it would be preferable not to collect and publish the asset tag and serial number data. I believe "bios_version" is a misnomer on our machines.
___
*[`api/node_info.go` line 7 at r1](https://reviewable.io/reviews/m-lab/nodeinfo/16#-NP-vGIN4jXEhXd5uKWv:-NP-vGIN4jXEhXd5uKWw:boz5vfh) ([raw file](https://github.com/m-lab/nodeinfo/blob/012a82c492f8859efe2f1c6190021102841918c1/api/node_info.go#L7)):*
> ```Go
> // parameters) and the output it generated.
> type CmdOut struct {
> 	CommandLine string
> ```

My thought is that we may want to preserve the `Datatype` field here to make BQ filters trivial (otherwise filters will need to grok the CommandLine, which is a little adhoc).

```
CommandLine
Datatype
Output
```


<!-- Sent from Reviewable.io -->

2023-02-27 12:29 UTC, SaiedKazemi commented
*[`config-new.json` line 7 at r1](https://reviewable.io/reviews/m-lab/nodeinfo/16#-NP-uu8qAi0KjyI1JzoE:-NPHq6a2-McxewyfJeey:b-ndqc1b) ([raw file](https://github.com/m-lab/nodeinfo/blob/012a82c492f8859efe2f1c6190021102841918c1/config-new.json#L7)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Does the new config need a `Filename` any more?
</blockquote></details>

No, we won't need either `Filename` or `Datatype`.  All we need is `Cmd`.


<!-- Sent from Reviewable.io -->

2023-02-27 12:37 UTC, SaiedKazemi commented
*[`config-new.json` line 73 at r1](https://reviewable.io/reviews/m-lab/nodeinfo/16#-NP-v0HX4YcwsAMEGiJx:-NPHrH3yCmzXty4QwT3C:bmouul2) ([raw file](https://github.com/m-lab/nodeinfo/blob/012a82c492f8859efe2f1c6190021102841918c1/config-new.json#L73)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Discussed with Shelbie, and I think it would be preferable not to collect and publish the asset tag and serial number data. I believe "bios_version" is a misnomer on our machines.
</blockquote></details>

OK, I will delete the two commands that currently collect `biosversion` and `chassisserial` datatypes.


<!-- Sent from Reviewable.io -->

2023-02-27 12:40 UTC, SaiedKazemi commented
*[`api/node_info.go` line 7 at r1](https://reviewable.io/reviews/m-lab/nodeinfo/16#-NP-vGIN4jXEhXd5uKWv:-NPHsN4fEQVpDDmTUf43:b-rmyllx) ([raw file](https://github.com/m-lab/nodeinfo/blob/012a82c492f8859efe2f1c6190021102841918c1/api/node_info.go#L7)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

My thought is that we may want to preserve the `Datatype` field here to make BQ filters trivial (otherwise filters will need to grok the CommandLine, which is a little adhoc).

```
CommandLine
Datatype
Output
```
</blockquote></details>

I agree that grokking the command line is ad hoc but let's not preserve the name `Datatype` because, IIUC, in M-Lab terminology `datatype` has a very special meaning and is associated with a BigQuery table.  How about `Infotype`?


<!-- Sent from Reviewable.io -->

2023-02-27 12:41 UTC, SaiedKazemi commented
Cool :)





<!-- Sent from Reviewable.io -->

2023-02-27 13:27 UTC, stephen-soltesz requested changes
> *[Reviewable](https://reviewable.io/reviews/m-lab/nodeinfo/16)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[`api/node_info.go` line 7 at r1](https://reviewable.io/reviews/m-lab/nodeinfo/16#-NP-vGIN4jXEhXd5uKWv:-NPI2Hau3w1NzhLc6wDU:b-g2a14l) ([raw file](https://github.com/m-lab/nodeinfo/blob/012a82c492f8859efe2f1c6190021102841918c1/api/node_info.go#L7)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

I agree that grokking the command line is ad hoc but let's not preserve the name `Datatype` because, IIUC, in M-Lab terminology `datatype` has a very special meaning and is associated with a BigQuery table.  How about `Infotype`?
</blockquote></details>

Other ideas,

* Name
* Format
* Type
* Kind


<!-- Sent from Reviewable.io -->

2023-02-27 15:07 UTC, SaiedKazemi commented
*[`api/node_info.go` line 7 at r1](https://reviewable.io/reviews/m-lab/nodeinfo/16#-NP-vGIN4jXEhXd5uKWv:-NPIPQK55BYVARbxIWxD:b-p573tc) ([raw file](https://github.com/m-lab/nodeinfo/blob/012a82c492f8859efe2f1c6190021102841918c1/api/node_info.go#L7)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Other ideas,

* Name
* Format
* Type
* Kind
</blockquote></details>

I changed `Datatype` to `Name`.


<!-- Sent from Reviewable.io -->

2023-02-27 15:12 UTC, stephen-soltesz reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/nodeinfo/16)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[`api/node_info.go` line 14 at r2](https://reviewable.io/reviews/m-lab/nodeinfo/16#-NPIPxJY8TKuS9NEFArL:-NPIPxJY8TKuS9NEFArM:b-1utt1g) ([raw file](https://github.com/m-lab/nodeinfo/blob/4a5311b38087b520f97fa702e34cac775c42c08a/api/node_info.go#L14)):*
> ```Go
> // NodeInfoV1 defines the list of executed commands and their outputs.
> type NodeInfoV1 struct {
> 	CommandOutput []CmdOut `json:"command_output"`
> ```

Followup thought. When considering the BQ schema and whether the field names match our conversational description of them, how about the following:

```
type NodeInfoV1 struct {
    Commands []CmdOut `json:"commands"`
}
```

Since `Commands` will be a repeated field, queries will regularly use an `UNNEST()` pattern, with a name, e.g.

```
SELECT command.Output
FROM `measurement-lab.host.nodeinfo`, UNNEST(commands) as command
WHERE command.Name = 'lspci'
```

That reads very easily and is self-describing.


<!-- Sent from Reviewable.io -->

2023-02-27 16:40 UTC, SaiedKazemi commented
*[`api/node_info.go` line 14 at r2](https://reviewable.io/reviews/m-lab/nodeinfo/16#-NPIPxJY8TKuS9NEFArL:-NPIjrKj7IyW27e0ZCwR:b-896fix) ([raw file](https://github.com/m-lab/nodeinfo/blob/4a5311b38087b520f97fa702e34cac775c42c08a/api/node_info.go#L14)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Followup thought. When considering the BQ schema and whether the field names match our conversational description of them, how about the following:

```
type NodeInfoV1 struct {
    Commands []CmdOut `json:"commands"`
}
```

Since `Commands` will be a repeated field, queries will regularly use an `UNNEST()` pattern, with a name, e.g.

```
SELECT command.Output
FROM `measurement-lab.host.nodeinfo`, UNNEST(commands) as command
WHERE command.Name = 'lspci'
```

That reads very easily and is self-describing.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-27 18:05 UTC, stephen-soltesz reviewed
> Reviewed 5 of 12 files at r2, 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/m-lab/nodeinfo/16)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[`main.go` line 66 at r3](https://reviewable.io/reviews/m-lab/nodeinfo/16#-NPJ0nPv8uasjJ5K29qc:-NPJ0nPv8uasjJ5K29qd:b-dlnxlv) ([raw file](https://github.com/m-lab/nodeinfo/blob/5c80318698afd06b5a5bc087f147288163d7de73/main.go#L66)):*
> ```Go
> 		g.Gather(t, *datadir, *smoketest, &nodeinfo)
> 	}
> 	// Now that we have gathered all data, marshal and write it out.
> ```

My instinct is that this new logic doesn't belong in `main()`. Did you consider a helper in the `data` package? 
___
*[`config/config.go` line 61 at r3](https://reviewable.io/reviews/m-lab/nodeinfo/16#-NPJ-0iOEnbF1-xnA8dP:-NPJ-0iOEnbF1-xnA8dQ:b-h5ben4) ([raw file](https://github.com/m-lab/nodeinfo/blob/5c80318698afd06b5a5bc087f147288163d7de73/config/config.go#L61)):*
> ```Go
> 			return fmt.Errorf("%#v is not a valid gatherer", g)
> 		}
> 		if err := uniformnames.Check(g.Name); err != nil {
> ```

I forgot we had this check package!

Though, we probably do not need to enforce this convention on the command name, since it will never appear in a file path, name, or BQ dataset or table name... though it may be a good stand-in to prevent overly complex names for now.
___
*[`data/gather.go` line 55 at r3](https://reviewable.io/reviews/m-lab/nodeinfo/16#-NPJ08nW15qU3fZGBMaL:-NPJ08nXCizQRdXaJ7ye:b-mu56p4) ([raw file](https://github.com/m-lab/nodeinfo/blob/5c80318698afd06b5a5bc087f147288163d7de73/data/gather.go#L55)):*
> ```Go
> 	out, err := exec.Command(g.Cmd[0], g.Cmd[1:]...).Output()
> 	if err != nil {
> 		logFatalf("failed to run command (error: %v)", err)
> ```

Previously `PanicOnError` was caught by the `recover()` clause in `Gather` and collection of other commands that will succeed could continue. A `log.Fatal` will exit the process and stop execution/collection of other commands.

Prefer allowing nodeinfo to continue running in this case. These failures could be transient. There is a metric in the `recover()` handler to monitor frequency of panics.


<!-- Sent from Reviewable.io -->

2023-03-01 10:02 UTC, SaiedKazemi commented
*[`main.go` line 66 at r3](https://reviewable.io/reviews/m-lab/nodeinfo/16#-NPJ0nPv8uasjJ5K29qc:-NPRaMc6CyUXm7viWj-2:biw2zut) ([raw file](https://github.com/m-lab/nodeinfo/blob/5c80318698afd06b5a5bc087f147288163d7de73/main.go#L66)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

My instinct is that this new logic doesn't belong in `main()`. Did you consider a helper in the `data` package? 
</blockquote></details>

Yes, I actually considered a helper function but because the design of the `data` package is focused on *gathering* data, I left the logic of *saving* the gathered data in the client of the package (`main` in this case).

Based on your comment, however, I have now added a `Save()` function to the `data` package.


<!-- Sent from Reviewable.io -->

2023-03-01 10:06 UTC, SaiedKazemi commented
*[`config/config.go` line 61 at r3](https://reviewable.io/reviews/m-lab/nodeinfo/16#-NPJ-0iOEnbF1-xnA8dP:-NPRcQg5AdtSub1V9Ip_:b-nn8vcv) ([raw file](https://github.com/m-lab/nodeinfo/blob/5c80318698afd06b5a5bc087f147288163d7de73/config/config.go#L61)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I forgot we had this check package!

Though, we probably do not need to enforce this convention on the command name, since it will never appear in a file path, name, or BQ dataset or table name... though it may be a good stand-in to prevent overly complex names for now.
</blockquote></details>

I am leaving the check in the code.  If it becomes too restrictive, we can remove it later.


<!-- Sent from Reviewable.io -->

2023-03-01 10:48 UTC, SaiedKazemi commented
*[`data/gather.go` line 55 at r3](https://reviewable.io/reviews/m-lab/nodeinfo/16#-NPJ08nW15qU3fZGBMaL:-NPRmUg_AndiA-D1tJ5m:b-896fix) ([raw file](https://github.com/m-lab/nodeinfo/blob/5c80318698afd06b5a5bc087f147288163d7de73/data/gather.go#L55)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Previously `PanicOnError` was caught by the `recover()` clause in `Gather` and collection of other commands that will succeed could continue. A `log.Fatal` will exit the process and stop execution/collection of other commands.

Prefer allowing nodeinfo to continue running in this case. These failures could be transient. There is a metric in the `recover()` handler to monitor frequency of panics.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-01 10:49 UTC, SaiedKazemi reviewed
Thank you for your review @stephen-soltesz . PTAL.

> *[Reviewable](https://reviewable.io/reviews/m-lab/nodeinfo/16#-:-NPRmba931xAiH3UvgJ8:bu1e1x7)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)



<!-- Sent from Reviewable.io -->

2023-03-01 13:24 UTC, stephen-soltesz approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/m-lab/nodeinfo/16#-:-NPSLAq-24BNDjalE_QC:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained



<!-- Sent from Reviewable.io -->

2023-03-01 14:08 UTC, merged